# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_auto_20170823_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('clicks', models.PositiveIntegerField()),
                ('refferer', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='url',
            name='tiny_url',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AddField(
            model_name='analytic',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='urls.Url'),
        ),
    ]
